# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-14 19:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_remote_submission', '0002_result'),
    ]

    operations = [
        migrations.RenameField(
            model_name='result',
            old_name='local_filename',
            new_name='local_file',
        ),
    ]
