# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-22 16:04
from __future__ import unicode_literals

from django.db import migrations, models
import django_remote_submission.models


class Migration(migrations.Migration):

    dependencies = [
        ('django_remote_submission', '0003_auto_20161214_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='interpreter',
            name='arguments',
            field=django_remote_submission.models.ListField(default=None, help_text='The arguments used when running the interpreter', max_length=256, verbose_name='Command Arguments'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='interpreter',
            name='path',
            field=models.CharField(help_text='The full path of the interpreter path.', max_length=256, verbose_name='Command Full Path'),
        ),
    ]
